void main()
{
  String ilce                 = "Şereflikoçhisar";
  String kita                 = "Kayıp Kıta Atlantis";
  String faks                 = "666 666 666";
  String postaKodu            = "6666";
  String instaAdresi          = "https://www.instagram.com/onurothan/";
  String calistiginBolum      = "Oyun Yazılım Geliştirme";
  int    urunMiktari          =  666;
  String musteriSoyadi        = "Othan";
  double odemeMiktari         =  666.666;
  String dogumTarihi          = "06/06/6666";
  double borc                 =  666.666;
  String medeniHal            = "Evli";
  String videoYorumu          = "Amazing!";
  String odemeSaati           = "06:06";
  double eftMiktari           =  666.666;
  int    satilanMiktar        =  666;
  String telefonModeli        = "Alcatel 666";
  String dergiAdi             = "Flutter Öğreniyorum";
  String basimTarihi          = "06/06/6666";
  double zamMiktari           =  666.666;
  int    daireSayisi          =  666;
  double enlem                =  666.666;
  double boylam               =  666.666;
  String yemekAdi             = "Şırdan";
  double urunFiyati           =  666.666;
  String sirket               = "Flutter LTD.ŞTİ.";
  String videoAdi             = "Flutter Video";
  String muzikSuresi          =  "66:66";
  double mekanPuani           =  66.6;
  String dosyaAdi             = "flutter.pdf";
  String resimFormati         = "PNG";
  String renk                 = "Siyah ve Beyaz (BJK)";
  int    renkKodu             =  666;
  String bilgisayarModeli     = "Garipoğlu 666";
  String ekranBoyutu          = "Dev Ekran:) şaka şaka 66.6 inç.";
  String kullanimSuresi       =  "666 Gün";
  int    basinc               =  666;
  String etkinlikGunu         = "Halloween Day";
  String odemeGunu            = "Ayın 32. Günü";
  String yolculukCikisTarihi  = "06/06/666";
  String mahalleAdi           = "Ankara Çinçin";
  String otobusHatti          = "500-T Tuzla";
  int    kullanilanDakika     =  666;
  String kargoTakipNo         = "666-W-666";
  String kuponSuresi          = "666 Gün";
  String kuponKodu            = "Beleş 666";
  String faturaTarihi         = "06/06/666";

  print("ilçe                           : $ilce");
  print("kıta                           : $kita");
  print("faks                           : $faks");
  print("posta kodu                     : $postaKodu");
  print("insta adresi                   : $instaAdresi");
  print("çalıştığın bölüm               : $calistiginBolum");
  print("ürün miktarı                   : $urunMiktari");
  print("müşteri soyadı                 : $musteriSoyadi");
  print("ödeme miktarı                  : $odemeMiktari");
  print("doğum tarihi                   : $dogumTarihi");
  print("borç                           : $borc");
  print("medeni hal                     : $medeniHal");
  print("video yorumu                   : $videoYorumu");
  print("ödeme saati                    : $odemeSaati");
  print("eft miktarı                    : $eftMiktari");
  print("satılan miktar                 : $satilanMiktar");
  print("telefon modeli                 : $telefonModeli");
  print("dergi adı                      : $dergiAdi");
  print("basım tarihi                   : $basimTarihi");
  print("zam miktarı                    : $zamMiktari");
  print("daire sayısı                   : $daireSayisi");
  print("enlem                          : $enlem");
  print("boylam                         : $boylam");
  print("yemek adı                      : $yemekAdi");
  print("ürün fiyatı                    : $urunFiyati");
  print("şirket                         : $sirket");
  print("video adı                      : $videoAdi");
  print("müzik süresi                   : $muzikSuresi");
  print("mekan puanı                    : $mekanPuani");
  print("dosya adı                      : $dosyaAdi");
  print("resim formatı                  : $resimFormati");
  print("renk                           : $renk");
  print("renk kodu                      : $renkKodu");
  print("ekran boyutu                   : $ekranBoyutu");
  print("kullanım süresi                : $kullanimSuresi");
  print("basınç                         : $basinc");
  print("etkinlik günü                  : $etkinlikGunu");
  print("bilgisayar modeli              : $bilgisayarModeli");
  print("ödeme günü                     : $odemeGunu");
  print("yolculuk cıkış tarihi          : $yolculukCikisTarihi");
  print("mahalle adı                    : $mahalleAdi");
  print("otobüs hattı                   : $otobusHatti");
  print("kullanılan dakika              : $kullanilanDakika");
  print("kargo takip no                 : $kargoTakipNo");
  print("kupon süresi                   : $kuponSuresi");
  print("kupon kodu                     : $kuponKodu");
  print("fatura tarihi                  : $faturaTarihi");

}